### ISSUE TITLE
Python Error When Trying to Convert via Traditional Method

### ISSUE THREAD

**Issue by scclark9** [Geontech/gr-component_converter#1]
Hello, 
I have been trying to run your GNURADIO to REDHAWK component converter example but I have been unable to complete the example conversion via the traditional method. I have RedHawk 2.0.6, GNURadio 3.7.11 and have successfully installed the integration package (I can see the SINK/SOURCE blocks in GNURadio). Below is a copy of the error traceback. Is there any suggestions to correct this?

./converter/run.py ./test/fm_example.grc 
Traceback (most recent call last):
  File "./converter/run.py", line 176, in <module>
    main(grc_file, destination, options)
  File "./converter/run.py", line 80, in main
    grc_to_py(grc_input, output_dir)
  File "/home/user/gnuradio-redhawk/gr-component_converter/converter/lib/grc_to_py.py", line 6, in grc_to_py
    platform = Platform()
  File "/prefix/default/lib64/python2.7/site-packages/gnuradio/grc/core/Platform.py", line 53, in __init__
    self.config = self.Config(*args, **kwargs)
TypeError: __init__() takes at least 3 arguments (1 given)

**Comment by btgoodwin** [comment]
Hello,

You'll notice that second to last line indicates the error is in GNURadio's GRC package.  The current converter tool only works with 3.7.9, which was the package manager -installed version in Ubuntu 16.04 for the demo.  

There are breaking API changes in GNURadio's python packages for GRC beginning at 3.7.10.  The modules were renamed, then APIs changed to have required parameters, etc.  This was discovered only in the last couple weeks since release, so the `README.md` was updated to reflect the specific version of GNURadio that is required for it to work properly.

Interestingly, the rest of the runtime API seems to work correctly between 3.7.9 through 3.7.11, it's just the GRC python package that is incompatible between minor revisions.  For example, if you use the docker-based container to run the converter, the resulting component and flow graph should run fine in your 3.7.11 environment with the exception of complex data output.

In that case, the integration package's `redhawk_sink` has a bug which doesn't configure the output data and SRI to correctly indicate complex data to REDHAWK (see [this](https://github.com/Geontech/gr-redhawk_integration_python/pull/1), just a guess of mine on how to fix it).  Real output works fine, however, as shown in the example.

**Comment by btgoodwin** [comment]
FYI - I patched out the issue I mentioned with the REDHAWK Integration Package, so complex data output should work fine now from the sink.

Were you able to revert back to GNURadio 3.7.9 or run the converter within the docker container?

**Comment by scclark9** [comment]
Sorry for feedback delay - the problem was indeed with the GNURadio version. I pulled GNURadio v3.7.9.3 from their tar ball repo and followed the from source instructions. I had tried modifying the grc_to_py.py to fix the package path break, but simply moving to the 3.7.9.x version fixed it. 

I ran into the complex data out issue as well - I'll pull your patch and give it a try. Thanks for the fast turnarounds!

**Comment by btgoodwin** [comment]
You're welcome! I'm glad you were able to get it squared away with the older version.

Unfortunately yes, the module name was the smallest issue.  The rest had more to do with the internals of that module, what arguments the methods need, etc., that stopped my short attempt.  I drilled down to the point where I found there is no longer a way to get the generator off the 3.7.11 version of the class, which we use to generate the top wrapper python file in the `grc_to_py.py` script.
